version: '3.10'

services:
  python:
    restart: always
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./ATMProject:/srv/www/ATMProject
    expose:
      - 8000
    ports:
      - 8000:8000
    command: > 
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  nginx:
    restart: always
    image: nginx:latest
    expose:
      - 8080
    ports:
      - "80:8080"
    volumes:
      - ./ATMProject/static:/srv/www/ATMProject/static
      - ./ATMProject/media:/srv/www/ATMProject/media
      - ./ATMProject/logs:/srv/www/ATMProject/logs
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - python