# Generated by Django 4.2.3 on 2023-09-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_alter_info_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='company',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
