# Generated by Django 4.2.5 on 2023-09-17 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0005_alter_info_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='info',
            name='fio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
