# Generated by Django 4.2.5 on 2023-09-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0006_alter_info_company_alter_info_email_alter_info_fio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='info',
            name='fio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
